agent:
  topology:
    probes:
      - docker

analyzer:
  listen: 0.0.0.0:8082
  topology:
    probes:
      - nsm
    nsm:
      servers:
        - 127.0.0.1:5007

etcd:
  data_dir: /tmp/skydive/etcd


